---
- name: Install docker engine(1/2)
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - curl
    - wget
    - ca-certificates
    - gnupg
    - lsb-release

- name: Install python-apt
  apt:
    name: python3-apt
    state: present

- name: Install python-pip
  apt:
    name: python3-pip
    state: present

- name: Start docker service
  service:
    name: docker
    state: started

- name: Install docker python module
  pip:
    name: docker

- name: Install docker engine(2/2)
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
  args:
    warn: no

# - name: Install docker and some dependencies
#   apt:
#     update_cache: yes
#     name: docker.io
#     state: installed

- name: Install docker engine(2/3)
  shell:  |
    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    warn: no

- name: Install docker engine(2/4)
  apt:
    update_cache: yes
    command:  >
        echo \
        "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install docker-ce docker-ce-cli containerd.io
    state: present

- name: Create the docker group
  shell: 'groupadd docker'

- name: Add your user to the docker group.
  shell: 'usermod -aG docker $USER'

- name: Log out and log back in so that your group membership is re-evaluated
  shell: 'newgrp docker'

- name: Create a data container
  docker_container:
    name: ubuntu
    image: ubuntu
    state: started
    recreate: yes
    volumes:
      - ubuntu:/ubuntu
    container_default_behavior: "compatibility"